# Library and data importing


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import string

In [2]:
data = pd.read_csv('cyberbullying_tweets.csv')
x = data.iloc[:,0:1].values
y = data.iloc[:,-1].values
data.cyberbullying_type.value_counts()

religion               7998
age                    7992
gender                 7973
ethnicity              7961
not_cyberbullying      7945
other_cyberbullying    7823
Name: cyberbullying_type, dtype: int64

In [3]:
data['tweet_text']

0        In other words #katandandre, your food was cra...
1        Why is #aussietv so white? #MKR #theblock #ImA...
2        @XochitlSuckkks a classy whore? Or more red ve...
3        @Jason_Gio meh. :P  thanks for the heads up, b...
4        @RudhoeEnglish This is an ISIS account pretend...
                               ...                        
47687    Black ppl aren't expected to do anything, depe...
47688    Turner did not withhold his disappointment. Tu...
47689    I swear to God. This dumb nigger bitch. I have...
47690    Yea fuck you RT @therealexel: IF YOURE A NIGGE...
47691    Bro. U gotta chill RT @CHILLShrammy: Dog FUCK ...
Name: tweet_text, Length: 47692, dtype: object

# Data Extraction

In [4]:
data.tweet_text=[doc.lower() for doc in data.tweet_text] 
#to lower string

In [5]:
string.punctuation
def remove_Punc(teststring):
    newstring = "".join([i for i in teststring if i not in string.punctuation])
    return newstring
data['tweet_text_1']=data['tweet_text'].apply(lambda x : remove_Punc(x))
data['tweet_text']=data['tweet_text_1']
data['tweet_text'] = [x.replace("\n\r","") for x in data['tweet_text']]
data.drop('tweet_text_1',axis=1,inplace=True)

In [6]:
data.head(20)

tweet_text cyberbullying_type
0   in other words katandandre your food was crapi...  not_cyberbullying
1   why is aussietv so white mkr theblock imaceleb...  not_cyberbullying
2   xochitlsuckkks a classy whore or more red velv...  not_cyberbullying
3   jasongio meh p  thanks for the heads up but no...  not_cyberbullying
4   rudhoeenglish this is an isis account pretendi...  not_cyberbullying
5   raja5aab quickieleaks yes the test of god is t...  not_cyberbullying
6   itu sekolah ya bukan tempat bully ga jauh kaya...  not_cyberbullying
7   karma i hope it bites kat on the butt she is j...  not_cyberbullying
8         stockputout everything but mostly my priest  not_cyberbullying
9   rebecca black drops out of school due to bullying  not_cyberbullying
10                       jordisdead httptcousqinyw5gn  not_cyberbullying
11        the bully flushes on kd httptwitvidcoma2tnp  not_cyberbullying
12                                         ughhhh mkr  not_cyberbullying
13  rt kurdsnews turkish state has killed 241 chil...  not_cyberbullying
14  love that the best response to the hotcakes th...  not_cyberbullying
15  yasmimcaci bferrarii parem de fazer bullying c...  not_cyberbullying
16  sarinhacoral victormaggi tadinhu de mim  sofre...  not_cyberbullying
17  0xabad1dea kelseytheodore2 twitter is basicall...  not_cyberbullying
18  best pick up line hi youre cute  i love how pe...  not_cyberbullying
19  now i gotta walk to classss i officially hate ...  not_cyberbullying

In [7]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\logan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [8]:
import re 
import emoji

def remove(string):
    string=re.sub(r'https?://\S+|www\.\S+','',string)
    string=re.sub(r'@[A-Za-z0-9]+','',string)
    string=re.sub(emoji.get_emoji_regexp(),'',string)
    string=re.sub(r'#','',string)
    return string

In [9]:
data['tweet_text']=data['tweet_text'].apply(lambda x: remove(x))

<ipython-input-8-64dc1a6a9175>:7: DeprecationWarning: 'emoji.get_emoji_regexp()' is deprecated and will be removed in version 2.0.0. If you want to remove emoji from a string, consider the method emoji.replace_emoji(str, replace='').
To hide this warning, pin/downgrade the package to 'emoji~=1.6.3'
  string=re.sub(emoji.get_emoji_regexp(),'',string)


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['cyberbullying_type'] = le.fit_transform(data['cyberbullying_type'])

In [11]:
data['cyberbullying_type'].value_counts()
#religion, age, gender, ethnicity, not, other

5    7998
0    7992
2    7973
1    7961
3    7945
4    7823
Name: cyberbullying_type, dtype: int64

In [12]:
data['tweet_text'][0].split()

['in',
 'other',
 'words',
 'katandandre',
 'your',
 'food',
 'was',
 'crapilicious',
 'mkr']

In [13]:
data.tweet_text[2]

'xochitlsuckkks a classy whore or more red velvet cupcakes'

In [14]:
#stemming and stopword (NLP)
corpus = []
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.extend(['rt', 'mkr', 'didn', 'bc', 'n', 'm', 'im', 'll', 'y', 've', 'u', 'ur', 'don', 't', 's','etc'])
x1 = ''
for i in range(0,data['tweet_text'].count()):
    tweet = data.tweet_text[i]
    tweet = tweet.split()
    for word in tweet:
        if not word in set(all_stopwords):
            x = ps.stem(word)
            x1 = x1 + ' ' + x
    corpus.append(x1) 
    x1=' '

In [15]:
print(corpus[47685:])

['  keithbishop64 true nice show watch racism incid ricki pick anybodi wasnt white', '  yourfavwhiteguy shut fuck upabout dumb app act like nag nigger', '  black ppl arent expect anyth depend anyth yet free particip work enjoy freedom human across globe wast energi past wast build futur', '  turner withhold disappoint turner call court “abomin conclav negro hate demons” one except “issu anoth decre color men women must driven jim crow car whenev suit whim white community”', '  swear god dumb nigger bitch got bleach hair reeeeeal fuckin soon dlt fuck', '  yea fuck therealexel your nigger fuck unfollow fuck dumb nigger', '  bro gotta chill chillshrammi dog fuck kp dumb nigger bitch lmao']


In [16]:
data['cyberbullying_type'].values

array([3, 3, 3, ..., 1, 1, 1])

# Creating a Bag-of-Words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 47692)
x = cv.fit_transform(corpus).toarray()
y = data.cyberbullying_type.values

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Start training (Naives Bayes)

In [19]:
#Naive Bayes
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(x_train, y_train)

MultinomialNB()

In [20]:
y_pred = classifier.predict(x_test)

In [21]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 4]
 [1 4]
 [5 5]
 ...
 [5 5]
 [3 3]
 [2 2]]


In [22]:
#confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1545    4    2    1    2    3]
 [  64 1496    9    3   16   39]
 [  42   45 1360   67   80   32]
 [ 281   67  124  531  398  171]
 [ 239  138   99  146  815   82]
 [   8    4    7   12    2 1605]]


0.7707306845581298

In [23]:
#false positive -> good !

In [24]:
import joblib
joblib.dump(classifier,'MulNB.pkl')

['MulNB.pkl']

# Random Forest

In [25]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [26]:
y_pred = classifier.predict(x_test)

In [27]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 4]
 [4 4]
 [5 5]
 ...
 [5 5]
 [3 3]
 [2 2]]


In [28]:
#confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm1 = confusion_matrix(y_test, y_pred)
print(cm1)
accuracy_score(y_test, y_pred)

[[1519    1    1   23   11    2]
 [   4 1595    4    7   14    3]
 [   4    5 1358  108  147    4]
 [  26    6   59  797  637   47]
 [  18    9   72  480  938    2]
 [   0    1   10   48   19 1560]]


0.8142362931124856

In [29]:
import joblib
joblib.dump(classifier,'RD.pkl')

['RD.pkl']

# Load 


In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
import joblib
joblib.load('RD.pkl')